title: Cylmat
desctiption: Cylmat provide explanation and tutorials about php and development
url: https://cylmat.github.io
permalink: ':title/'

markdown: kramdown
full-version: https://cylmat.github.io

sass:
    style: compressed
  
#optimization
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge

# Tracker
analytics: UA

# Comments
disqus-shortname: cylmat-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
